[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
startCommand = "sh ./start.sh"

[service]
health_check_path = "/api/health"
internal_port = 3000
port = 3000 